apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: default
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 36000000
    image: ubuntu
    imagePullPolicy: IfNotPresent
    name: test
    resources:
      requests:
        cpu: 10m
  dnsPolicy: ClusterFirst
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
