apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - image: ubuntu
    name: test
    volumeMounts:
    - mountPath: /vuln
      name: vuln-vol
    command: ["sleep"]
    args: ["10000"]
  volumes:
  - name: vuln-vol
    hostPath:
      path: /
